apiVersion: v1
kind: ReplicationController
metadata:
  name: app-maroon
  labels:
    name: app
spec:
  replicas: 3
  selector:
    name: app
    colour: maroon
  template:
    metadata:
      labels:
        name: app
        colour: maroon
    spec:
      containers:
        - name: app
          image: becram/djangogirls-app:1.3-maroon
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_DB
              value: app_db
            - name: POSTGRES_HOST
              value: postgres-service
          ports:
            - containerPort: 8000
