apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcPostgres.name }}
spec:
  storageClassName: {{ .Values.scPostgres.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvcPostgres.storage }}