#!/bin/bash

curl  -fsSL https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
sudo kubectl -n kube-system create serviceaccount tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller

kubectl get pods --namespace kube-system
