apiVersion: apps/v1
kind: Deployment
{{- include "django_metadata" . }}

spec:
  replicas: {{ .Values.rcDjango.replicaCount }}
  strategy:
    type: Recreate
  selector:
      matchLabels:
        app: django-k8s-worker
  template:
    {{- include "django_metadata" . | indent 4 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/postgres-secrets.yaml") . | sha256sum }}
    spec:
      containers:
        - name: django-app
          image: {{ .Values.rcDjango.repository }}:{{ .Values.rcDjango.tag }}
          imagePullPolicy: {{ .Values.rcDjango.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.rcDjango.cpuLimit | quote }}
              memory: {{ .Values.rcDjango.memoryLimit | quote }}
            requests:
              cpu: {{ .Values.rcDjango.cpuRequest | quote }}
              memory: {{ .Values.rcDjango.memoryRequest | quote}}
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres_user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres_password


            - name: POSTGRES_DB
              value: app_db
            - name: POSTGRES_HOST
              value: {{ .Chart.Name }}-postgres
          ports:
            - containerPort: {{ .Values.rcDjango.containerPort }}



















