apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django-migrations
          image: {{ .Values.rcDjango.repository }}:{{ .Values.rcDjango.tag }}
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              value: app_db
            - name: POSTGRES_HOST
              value: {{ .Chart.Name }}-postgres
      restartPolicy: Never
  backoffLimit: 5
