
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  labels:
    {{- include "base_labels" . | indent 4 }}
    {{ .Values.appIdentifier }}: {{ .Values.rcDjango.app }}
type: Opaque
data:
  postgres_password: {{ default "" .Values.secrets.postgres_password | b64enc | quote }}
  postgres_user: {{ default "" .Values.secrets.postgres_user | b64enc | quote }}
