
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
  labels:
    {{- include "base_labels" . | indent 4 }}
    {{ .Values.appIdentifier }}: {{ .Values.rcDjango.app }}
type: Opaque
data:
  {{ if .Values.secrets.username }}
  password: {{ default "" .Values.secrets.password | b64enc | quote }}
  {{ else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  username: {{ default "" .Values.secrets.username | b64enc | quote }}